image: node:lts-alpine

variables:
  DOCKER_DRIVER: overlay
  IMAGE_VERSION: $CI_PIPELINE_ID
  HOST: "94.250.254.108"

stages:
  - build site
  - build image
  - deploy

build site:
  stage: build site
  script:
    - npm install
    - npm run build
  only:
    - master
  artifacts:
    paths:
    - dist

build docker image:
  image: docker:latest
  stage: build image
  services: ['docker:dind']
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE -f docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE

deploy:
  image: pwinik/ansible
  stage: deploy
  script:
     - >
      ansible-playbook
      -i $HOST,
      docker/deploy.yaml
      -u root
      -e REGISTRY_LOGIN="\"gitlab-ci-token\""
      -e REGISTRY_PASSWORD="\"$CI_JOB_TOKEN\""
      -e REGISTRY_URL="\"$CI_REGISTRY\""
      -e IMAGE_NAME="\"$CI_REGISTRY_IMAGE\""
      -e IMAGE_VERSION="\"$IMAGE_VERSION\""
