image: node:lts-alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mkdir public
    - mv dist/* public
  artifacts:
    paths:
    - public
  only:
  - master
