image: node:lts-alpine

variables:
  DOCKER_DRIVER: overlay

stages:
  - build site
  - build image
  - deploy

build site:
  stage: build site
  script:
    - npm install
    - npm run build
  only:
    - master
  artifacts:
    paths:
    - dist

build docker image:
  image: docker:latest
  stage: build image
  services: ['docker:dind']
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
