image: node:lts-alpine

variables:
  DOCKER_DRIVER: overlay
  IMAGE_VERSION: $CI_PIPELINE_ID
  DOMAIN: "myrt.co"

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - node_modules/

stages:
  - build
  - quality assurance
  - dockerize
  - deploy
  - metrics
  - upload metrics

include:
  - local: ".gitlab/ci/build.gitlab-ci.yml"
  - local: ".gitlab/ci/qa.gitlab-ci.yml"
  - local: ".gitlab/ci/dockerize.gitlab-ci.yml"
  - local: ".gitlab/ci/deploy.gitlab-ci.yml"
  - local: ".gitlab/ci/metrics.gitlab-ci.yml"
  - local: ".gitlab/ci/pages.gitlab-ci.yml"
