---
- hosts: "{{ target }}"
  name: Deploy myrt.co

  vars:
    image_repository: ghcr.io/mishamyrt/myrt.co/site
    image_tag: latest

  tasks:
    - name: Log in to GitHub Container Registry
      when: registry_token is defined and registry_token | length > 0
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "{{ registry_username | default('mishamyrt') }}"
        password: "{{ registry_token }}"

    - name: Pull image
      community.docker.docker_image:
        name: "{{ image_repository }}:{{ image_tag }}"
        source: pull
        force_source: true

    - name: Start container
      community.docker.docker_container:
        image: "{{ image_repository }}:{{ image_tag }}"
        recreate: true
        pull: false
        state: started
        restart_policy: unless-stopped
        name: "myrt-co-{{ target }}"
        ports:
          - 80:80
          - 443:443
