#!/bin/bash
get_staged () {
  git diff --name-only --cached | grep .$1
}

lint () {
  files=$(get_staged $1)
  if [ -z "$files" ]; then
    return 0
  else
    npx $2 $files && return 0
  fi
  return 1
}

lint js standardx && lint scss stylelint && lint pug pug-lint
