#!/usr/bin/env node
const { readFile, writeFile } = require('fs').promises
const path = require('path')

const allowedBranches = [
  'feature',
  'hotfix',
  'support',
  'release',
  'bugfix',
  'develop',
  'master'
]

const commitFilePath = path.join(process.cwd(), '..', 'COMMIT_EDITMSG')

const headFilePath = path.join(process.cwd(), '..', 'HEAD')

const getBranchParts = head =>
  head.split('/').slice(2).map(part => part.trim())

const isValidBranchName = parts =>
  parts.length > 1 && allowedBranches.includes(parts[0])

run: (async () => {
  const headContent = await readFile(headFilePath)
  const branchParts = getBranchParts(headContent.toString())
  if (!isValidBranchName(branchParts)) {
    console.error('Wrong branch name')
    console.info('Branch should be in Git Flow format')
    process.exit(1)
  }

  const message = await readFile(commitFilePath)
  await writeFile(commitFilePath, `${branchParts[1]}: ${message}`)
})()
