---
- hosts: "myrt-co"
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: "Log into private registry and force re-authorization"
      docker_login:
        registry: "docker.pkg.github.com"
        username: "{{ REGISTRY_USERNAME }}"
        password: "{{ REGISTRY_PASSWORD }}"
        reauthorize: yes

    - name: "Recreate Docker image"
      docker_container:
        name: "myrt-co"
        image: "{{ IMAGE_NAME }}"
        recreate: "yes"
        restart_policy: "always"
        pull: "yes"
        ports:
          - "443:443"
          - "80:80"
        volumes:
          - "/etc/letsencrypt/:/etc/letsencrypt/"
