name: Build `dev` image

on:
  push:
    branches:
      - develop

jobs:
  build_static:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build static files
      run: npm run build

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

  build_image:
    needs: build_static
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Download build results
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist/

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        no-cache: true
        push: true
        file: ./docker/Dockerfile
        tags: docker.pkg.github.com/mishamyrt/myrt.co/site:dev

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

