name: Build `dev` image

on:
  push:
    branches:
      - develop

env:
  registry: docker.pkg.github.com

jobs:
  build_static:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build static files
      run: npm run build

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

  build_image:
    needs: build_static
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Download build results
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist/

    - name: Login to GitHub Docker registry
      env:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: docker login $registry -u $username -p $password

    - name: Build image
      run: docker build -t $registry/$GITHUB_REPOSITORY/site:dev -f docker/Dockerfile .

    - name: Push image
      run: docker push $registry/$GITHUB_REPOSITORY/site:dev
