name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build_static:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: npm ci
    - name: Build static files
      run: npm run build
    - name: Upload results
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/

  build_image:
    needs: build_static
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download build results
      uses: actions/download-artifact@v1
      with:
        name: dist
    - name: Login to Docker Hub
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: echo -n $DOCKER_TOKEN | docker login -u mishamyrt --password-stdin
    - name: Build image
      run: docker build -t mishamyrt/myrt-co:latest -f docker/Dockerfile .
    - name: Push image
      run: docker push mishamyrt/myrt-co


  deploy_image:
    needs: build_image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Deploy latest image to myrt.co
      env:
        SSH_PRIVATE_KEY_B64: ${{ secrets.SSH_PRIVATE_KEY_B64 }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        eval $(ssh-agent -s)
        echo $SSH_PRIVATE_KEY_B64 | base64 -d | tr -d '\r' > private.key
        echo >> private.key
        chmod 600 private.key
        cat private.key | ssh-add -
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        chmod 700 ~/.ssh
        chmod 644 ~/.ssh/known_hosts
        ssh-keyscan -t rsa myrt.co >> ~/.ssh/known_hosts
        ansible-playbook -i ansible/hosts ansible/deploy.yml \
          -e REGISTRY_PASSWORD=$DOCKER_TOKEN \
          -e IMAGE_VERSION=latest
