name: Deploy production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://myrt.co
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build tar image
        run: sh -c scripts/build-tar.sh

      - name: Run deploy playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy/playbook.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory deploy/hosts.yaml
            --extra-vars target=production
            --verbose
