name: Deploy to staging environment

on:
  push:
    branches:
      - develop

env:
  STAGING_DOMAIN: "myrt-staging.surge.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build static files
        run: npm run build

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy_staging:
    name: deploy to surge
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build results
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Install surge
        run: sudo npm install -g surge

      - uses: chrnorm/deployment-action@v1.2.0
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ secrets.API_TOKEN }}
          target_url: https://myrt-staging.surge.sh
          environment: staging

      - name: Upload to surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: surge --project ./dist -d "$TEST_DOMAIN" --token "$SURGE_TOKEN"

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v1.0.0
        with:
          token: ${{ secrets.API_TOKEN }}
          environment_url: https://myrt-staging.surge.sh
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v1.0.0
        with:
          token: ${{ secrets.API_TOKEN }}
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
