name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Rebuild image
      run: npm run build:docker

    - name: Stop container
      run: npm run stop:docker

    - name: Start container
      run: npm run start:docker
