name: Metrics

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://myrt.co/en/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: lighthouse-report
        path: './report'

  sitespeed:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      run: |
        wget -O ./gitlab-exporter/index.js https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js
        mkdir sitespeed-results
        docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.3.1 --plugins.add ./gitlab-exporter --outputFolder sitespeed-results $URL
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: sitespeed-report
        path: './sitespeed-results'

  publish:
    needs: [lighthouse, sitespeed]
    runs-on: ubuntu-latest
    steps:
    - name: Download lighthouse report
      uses: actions/download-artifact@v1
      with:
        name: lighthouse-report
    - name: Download sitespeed report
      uses: actions/download-artifact@v1
      with:
        name: sitespeed-report
    - name: Prepare deploy
      run: |
        mkdir public
        mv sitespeed-report public/sitespeed
        mkdir public/lighthouse
        mv lighthouse-report/https___myrt_co_en_.report.html public/lighthouse/index.html
        mv lighthouse-report/https___myrt_co_en_.report.json public/lighthouse/report.json
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@master
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
