name: Metrics

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://myrt.co/en/'
    - name: Rename files
      run: |
        mv report/https___myrt_co_en_.report.html report/index.html
        mv report/https___myrt_co_en_.report.json report/report.json
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: lighthouse-report
        path: './report'

  publish:
    needs: lighthouse
    runs-on: ubuntu-latest
    steps:
    - name: Download lighthouse report
      uses: actions/download-artifact@v1
      with:
        name: lighthouse-report
    - name: Prepare deploy
      run: |
        mkdir public
        mv lighthouse-report/ public/lighthouse-report/
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@master
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
