name: Quality assurance

on:
  - push

env:
  PNPM_VERSION: '8.13.1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Install dependencies
      run: pnpm install

    - name: Build check
      run: pnpm build

    - name: Spell check
      run: pnpm spell-check

    - name: Docker build check
      run: docker build .
