generate static files:
  stage: build
  variables:
    PARCEL_WORKERS: 1
    NODE_ENV: production
  script:
    - rm -rf node_modules/
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
