deploy to myrt.co:
  only:
    - master
  image: pwinik/ansible
  stage: deploy
  cache: {}
  environment:
    name: Production
    url: "https://$DOMAIN"
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - chmod 644 ~/.ssh/known_hosts
  script:
    - >
      ansible-playbook
      -i $DEPLOY_HOST,
      docker/deploy.yml
      -u root
      -e REGISTRY_LOGIN="\"gitlab-ci-token\""
      -e REGISTRY_PASSWORD="\"$CI_JOB_TOKEN\""
      -e REGISTRY_URL="\"$CI_REGISTRY\""
      -e IMAGE_NAME="\"$CI_REGISTRY_IMAGE\""
      -e IMAGE_VERSION="\"$IMAGE_VERSION\""
