lighthouse:
  image: markhobson/node-chrome
  cache: {}
  stage: metrics
  # only:
  #   - master
  #   - tags
  variables:
    PAGE_URL: https://$DOMAIN/en/
  before_script:
    - npm install -g lighthouse
  script:
    - lighthouse --chrome-flags="--headless --no-sandbox" $PAGE_URL --output html --output-path ./lighthouse-report.html
  artifacts:
    paths:
      - ./lighthouse-report.html
    expire_in: 1 week

sitespeed.io:
  image: docker:git
  cache: {}
  # only:
  #   - master
  #   - tags
  stage: metrics
  variables:
    URL: https://$DOMAIN/en/
  services:
    - docker:stable-dind
  script:
    - mkdir gitlab-exporter
    - wget -O ./gitlab-exporter/index.js https://gitlab.com/gitlab-org/gl-performance/raw/master/index.js
    - mkdir sitespeed-results
    - docker run --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.3.1 --plugins.add ./gitlab-exporter --outputFolder sitespeed-results $URL
  artifacts:
    paths:
      - sitespeed-results
