lighthouse:
  image: markhobson/node-chrome
  cache: {}
  stage: metrics
  only:
    - master
  variables:
    PAGE_URL: https://$DOMAIN/en/
  before_script:
    - npm install -g lighthouse
  script:
    - lighthouse --chrome-flags="--headless --no-sandbox" $PAGE_URL --output html --output-path ./lighthouse-report.html
  artifacts:
    paths:
      - ./lighthouse-report.html
    expire_in: 1 week
