pages:
  stage: upload metrics
  image: alpine:latest
  cache: {}
  script:
    - mkdir public
    - mkdir public/lighthouse
    - mv lighthouse-report.html public/lighthouse/index.html
    - mv sitespeed-results/ public/sitespeed-results
  artifacts:
    paths:
      - public
  only:
    - master
