spell check:
  stage: quality assurance
  before_script:
    - npm install
  script:
    - npm run spell-check

codestyle check:
  stage: quality assurance
  before_script:
    - npm install
  script:
    - npm run lint
